; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EMS Command Center"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Zaid Top Solution"
#define MyAppExeName "EMS.Frontend.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{5E58A48B-22F2-4467-92B1-4A59EE9A0D8D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=no
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; We want administrative install to write to Program Files and register properly
PrivilegesRequired=admin
OutputDir=.
OutputBaseFilename=EMS_Command_Center_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "PublishOutput\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "PublishOutput\appsettings.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "PublishOutput\*.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "PublishOutput\*.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "PublishOutput\DB\*"; DestDir: "{app}\DB"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "PublishOutput\LatoFont\*"; DestDir: "{app}\LatoFont"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "PublishOutput\Resources\*"; DestDir: "{app}\Resources"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "PublishOutput\runtimes\*"; DestDir: "{app}\runtimes"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
