// <auto-generated />
using System;
using Keemya.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Keemya.Backend.Migrations
{
    [DbContext(typeof(KeemyaDbContext))]
    [Migration("20260520080802_AddIsSystemDefault")]
    partial class AddIsSystemDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Keemya.Backend.Models.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("AlertTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AlertTypeId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("Keemya.Backend.Models.AlertType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AlertTypes");
                });

            modelBuilder.Entity("Keemya.Backend.Models.AudioFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AudioFiles");
                });

            modelBuilder.Entity("Keemya.Backend.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EntityData")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Keemya.Backend.Models.CommandConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AudioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CommandHex")
                        .HasColumnType("int");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedResponseBytes")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AudioId");

                    b.ToTable("CommandConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Color = "Blue",
                            CommandHex = 0,
                            CommandType = "Clear",
                            Description = "Clears any event in progress.",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Clear"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Color = "Red",
                            CommandHex = 1,
                            CommandType = "Wail",
                            Description = "Wail tone warning.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Wail"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Color = "Red",
                            CommandHex = 2,
                            CommandType = "Attack",
                            Description = "Attack tone warning.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Attack"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Color = "Orange",
                            CommandHex = 3,
                            CommandType = "Alert",
                            Description = "Alert tone warning.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Alert"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            Color = "Purple",
                            CommandHex = 4,
                            CommandType = "PublicAddress",
                            Description = "Live public address — tone generator bypassed.",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Public Address"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            Color = "Orange",
                            CommandHex = 5,
                            CommandType = "AirHorn",
                            Description = "Air horn tone warning.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Air Horn"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            Color = "Yellow",
                            CommandHex = 6,
                            CommandType = "HiLo",
                            Description = "Hi-Lo tone warning.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Hi-Lo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            Color = "Yellow",
                            CommandHex = 7,
                            CommandType = "Whoop",
                            Description = "Whoop tone warning.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Whoop"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            Color = "Green",
                            CommandHex = 8,
                            CommandType = "NoonTest",
                            Description = "Short wail-2 tone (noon test).",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Noon Test"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            Color = "Cyan",
                            CommandHex = 15,
                            CommandType = "SilentTest",
                            Description = "Initiates diagnostic silent test, produces a status response.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Silent Test"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Color = "Blue",
                            CommandHex = 31,
                            CommandType = "StatusRequest",
                            Description = "Retrieves the full status byte from the siren.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Status Request"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Color = "Green",
                            CommandHex = 24,
                            CommandType = "ArmSystem",
                            Description = "Arms the Instant Status response.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Arm System"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Color = "Red",
                            CommandHex = 25,
                            CommandType = "DisarmSystem",
                            Description = "Disables the Instant Status response.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Dis-arm System"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Color = "Green",
                            CommandHex = 26,
                            CommandType = "SirenOn",
                            Description = "Enables the tone generator and digital voice.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Siren On"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Color = "Red",
                            CommandHex = 27,
                            CommandType = "SirenOff",
                            Description = "Disables the tone generator; digital voice stays active.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Siren Off"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            Color = "Cyan",
                            CommandHex = 35,
                            CommandType = "InstantStatus",
                            Description = "Get real-time instant status of the remote siren station.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Instant Status"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000007"),
                            Color = "Blue",
                            CommandHex = 22,
                            CommandType = "Counter",
                            Description = "Tone activation software counter request.",
                            Duration = 0,
                            ExpectedResponseBytes = 2,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Counter"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000008"),
                            Color = "Blue",
                            CommandHex = 23,
                            CommandType = "ClearCounter",
                            Description = "Clears the software tone activation counter to zero.",
                            Duration = 0,
                            ExpectedResponseBytes = 2,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Clear Counter"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000009"),
                            Color = "Blue",
                            CommandHex = 30,
                            CommandType = "TestClear",
                            Description = "Clears LEDs.",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Test Clear"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000010"),
                            Color = "Green",
                            CommandHex = 33,
                            CommandType = "BatteryAC",
                            Description = "Requests battery DC voltage and AC voltage measurements.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Battery / AC"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000011"),
                            Color = "Green",
                            CommandHex = 34,
                            CommandType = "BatteryTemp",
                            Description = "Requests battery DC voltage and cabinet temperature.",
                            Duration = 0,
                            ExpectedResponseBytes = 4,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Battery / Temp"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000012"),
                            Color = "Orange",
                            CommandHex = 36,
                            CommandType = "TransmitOff",
                            Description = "Disables the transmit repeat feature during Instant Status.",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Transmit Off"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Color = "Purple",
                            CommandHex = 17,
                            CommandType = "Message13",
                            Description = "Initiates digital voice message 13 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 13"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Color = "Purple",
                            CommandHex = 18,
                            CommandType = "Message14",
                            Description = "Initiates digital voice message 14 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 14"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Color = "Purple",
                            CommandHex = 19,
                            CommandType = "Message15",
                            Description = "Initiates digital voice message 15 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 15"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Color = "Purple",
                            CommandHex = 20,
                            CommandType = "Message16",
                            Description = "Initiates digital voice message 16 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 16"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            Color = "Purple",
                            CommandHex = 49,
                            CommandType = "Message1",
                            Description = "Initiates digital voice message 1 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            Color = "Purple",
                            CommandHex = 50,
                            CommandType = "Message2",
                            Description = "Initiates digital voice message 2 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000003"),
                            Color = "Purple",
                            CommandHex = 51,
                            CommandType = "Message3",
                            Description = "Initiates digital voice message 3 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000004"),
                            Color = "Purple",
                            CommandHex = 52,
                            CommandType = "Message4",
                            Description = "Initiates digital voice message 4 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 4"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000005"),
                            Color = "Purple",
                            CommandHex = 53,
                            CommandType = "Message5",
                            Description = "Initiates digital voice message 5 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 5"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000006"),
                            Color = "Purple",
                            CommandHex = 54,
                            CommandType = "Message6",
                            Description = "Initiates digital voice message 6 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 6"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000007"),
                            Color = "Purple",
                            CommandHex = 55,
                            CommandType = "Message7",
                            Description = "Initiates digital voice message 7 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 7"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000008"),
                            Color = "Purple",
                            CommandHex = 56,
                            CommandType = "Message8",
                            Description = "Initiates digital voice message 8 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 8"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000009"),
                            Color = "Purple",
                            CommandHex = 59,
                            CommandType = "Message9",
                            Description = "Initiates digital voice message 9 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 9"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000010"),
                            Color = "Purple",
                            CommandHex = 60,
                            CommandType = "Message10",
                            Description = "Initiates digital voice message 10 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 10"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000011"),
                            Color = "Purple",
                            CommandHex = 61,
                            CommandType = "Message11",
                            Description = "Initiates digital voice message 11 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 11"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000012"),
                            Color = "Purple",
                            CommandHex = 62,
                            CommandType = "Message12",
                            Description = "Initiates digital voice message 12 (RSDVM module).",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Message 12"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            Color = "Yellow",
                            CommandHex = 57,
                            CommandType = "StrobeOn",
                            Description = "Activates the strobe light.",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Strobe On"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            Color = "Yellow",
                            CommandHex = 58,
                            CommandType = "StrobeOff",
                            Description = "De-activates the strobe light.",
                            Duration = 0,
                            ExpectedResponseBytes = 0,
                            IsEnabled = true,
                            IsSystemDefault = true,
                            Name = "Strobe Off"
                        });
                });

            modelBuilder.Entity("Keemya.Backend.Models.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NotificationTemplates");
                });

            modelBuilder.Entity("Keemya.Backend.Models.Privilege", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Privileges");
                });

            modelBuilder.Entity("Keemya.Backend.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Keemya.Backend.Models.SirenDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HardwareModel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastHealthCheck")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SirenDeviceId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SirenDeviceId")
                        .IsUnique();

                    b.ToTable("SirenDetails");
                });

            modelBuilder.Entity("Keemya.Backend.Models.SirenDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Lat")
                        .HasColumnType("double");

                    b.Property<double>("Lng")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Redundant")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("SirenDevices");
                });

            modelBuilder.Entity("Keemya.Backend.Models.SirenGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SirenGroups");
                });

            modelBuilder.Entity("Keemya.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFirstTimeLogin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            IsFirstTimeLogin = false,
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Keemya.Backend.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("PrivilegeRole", b =>
                {
                    b.Property<Guid>("PrivilegesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("char(36)");

                    b.HasKey("PrivilegesId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolePrivileges", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("char(36)");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Keemya.Backend.Models.AlertRule", b =>
                {
                    b.HasOne("Keemya.Backend.Models.AlertType", "AlertType")
                        .WithOne("AlertRule")
                        .HasForeignKey("Keemya.Backend.Models.AlertRule", "AlertTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Keemya.Backend.Models.NotificationTemplate", "Template")
                        .WithMany("AlertRules")
                        .HasForeignKey("TemplateId");

                    b.Navigation("AlertType");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Keemya.Backend.Models.CommandConfig", b =>
                {
                    b.HasOne("Keemya.Backend.Models.AudioFile", "AudioFile")
                        .WithMany("CommandConfigs")
                        .HasForeignKey("AudioId");

                    b.Navigation("AudioFile");
                });

            modelBuilder.Entity("Keemya.Backend.Models.SirenDetails", b =>
                {
                    b.HasOne("Keemya.Backend.Models.SirenDevice", "SirenDevice")
                        .WithOne("Details")
                        .HasForeignKey("Keemya.Backend.Models.SirenDetails", "SirenDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SirenDevice");
                });

            modelBuilder.Entity("Keemya.Backend.Models.SirenDevice", b =>
                {
                    b.HasOne("Keemya.Backend.Models.SirenGroup", "Group")
                        .WithMany("Devices")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Keemya.Backend.Models.UserProfile", b =>
                {
                    b.HasOne("Keemya.Backend.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Keemya.Backend.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrivilegeRole", b =>
                {
                    b.HasOne("Keemya.Backend.Models.Privilege", null)
                        .WithMany()
                        .HasForeignKey("PrivilegesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Keemya.Backend.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Keemya.Backend.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Keemya.Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Keemya.Backend.Models.AlertType", b =>
                {
                    b.Navigation("AlertRule")
                        .IsRequired();
                });

            modelBuilder.Entity("Keemya.Backend.Models.AudioFile", b =>
                {
                    b.Navigation("CommandConfigs");
                });

            modelBuilder.Entity("Keemya.Backend.Models.NotificationTemplate", b =>
                {
                    b.Navigation("AlertRules");
                });

            modelBuilder.Entity("Keemya.Backend.Models.SirenDevice", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Keemya.Backend.Models.SirenGroup", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Keemya.Backend.Models.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
